{% set name = "rpaframework-core" %}
{% set version = "6.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rpaframework-core-{{ version }}.tar.gz
  sha256: 51e1bbcfa092bc540fe8b3389942c55d97ffc48339401e4b928c1e8ff62f8e93

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<4.0
  run:
    - python >=3.6,<4.0
    - selenium >=3.141.0,<4.0.0
    - webdrivermanager >=0.10.0,<0.11.0

test:
  imports:
    - RPA
    - RPA.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://rpaframework.org/
  summary: Core utilities used by RPA Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - osrjv
    - xylix
    - kariharju
