{% set name = "rpaframework-core" %}
{% set version = "11.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rpaframework_core-{{ version }}.tar.gz
  sha256: 1276779c35bfc97b12fc1852f57b62d4e42962b9d0b72ad68f23fa49b1057065

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - selenium >=4.6.1,<5.0.0
    - webdriver-manager ==4.0.0
    - psutil >=5.9.0,<6.0.0
    - pywin32-on-windows
# PiP Check Failure:rpaframework-core 11.2.0 has requirement pywin32<304,>=300    
    - pywin32 >=300,<304
    - uiautomation >=2.0.15,<3.0.0  # [win]
# PiP Check Failure: uiautomation 2.0.18 requires typing, which is not installed.    
    - typing
    - pillow >=9.1.1,<10.0.0
    - packaging >=23.1.0,<24.0.0
    - __linux  # [linux]
    - __osx    # [osx]
    - __win    # [win]

test:
  imports:
    - RPA
    - RPA.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://rpaframework.org/
  summary: Core utilities used by RPA Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kariharju
    - osrjv
    - rxm7706
    - xylix
