{% set name = "rpaframework-core" %}
{% set version = "7.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rpaframework-core-{{ version }}.tar.gz
  sha256: 2e27292c8f4f2a171df1f2eede93ddbb52402b1d8e89b565c45adb3fd65f373b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<4.0
  run:
    - python >=3.6,<4.0
    - selenium >=3.141.0,<4.0.0
    - webdrivermanager >=0.10.0,<0.11.0

test:
  imports:
    - RPA
    - RPA.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://rpaframework.org/
  summary: Core utilities used by RPA Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - osrjv
    - xylix
    - kariharju
