{% set name = "rpaframework-core" %}
{% set version = "11.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rpaframework_core-{{ version }}.tar.gz
  sha256: e15e8bc3a4b058e4bb627c7cc42fe594f3ff750f7cdfa178b886b18fe6514af2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core >=1.0.0
    - pip

  run:
    - python >=3.7.0,<4.0.0
    - selenium >=4.6.1,<5.0.0
    - webdriver-manager >=3.9.1,<4.0.0
    - pillow >=9.1.1,<10.0.0
    - packaging >=21.3,<24

    #- psutil >=5.9.0,<6.0.0
    #- pywin32-on-windows >=300,<304
    #- uiautomation >=2.0.15,<3.0.0

test:
  imports:
    - RPA
    - RPA.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://rpaframework.org/
  summary: Core utilities used by RPA Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - osrjv
    - xylix
    - kariharju
